### ISSUE TITLE
I don't want winmac to install some components that I already have

### ISSUE THREAD

**Issue by Dhyfer1** [Asteski/WinMac#1]
Hi @Asteski 

Thanks for Winmac. I have a question, before knowing Winmac I am already using PowerToys, Startallback and Everything. So how do I edit the script file so that it does not download these 3 components? Since they are already installed before I wanted to use winmac, then I don't want winmac to download and install them.

That's all.

**Comment by Asteski** [comment]
Hello,

it should not reinstall utilities if they already exist, unless an update is required. Will test it today, thanks!

**Comment by Dhyfer1** [comment]
Thank you so much. That's what I want, to be able to select what I want to install, and also for the script to be able to uninstall winmac as well.

**Comment by Asteski** [comment]
Here's an update with custom install and uninstall capabilties https://github.com/Asteski/WinMac/releases/tag/v0.3.2

**Comment by Dhyfer1** [comment]
Thank you so much. The new custom install and uninstall script work very well, although the only thing I don't like is that after installing Winmac the recycle bin disappears from the desktop. 🫤

I thought that the uninstall.ps1 file was also used to uninstall winmac, but it is not. ![ResizedImage_2024-05-05_23-59-21_2638.png](https://github.com/Asteski/WinMac/assets/50301201/dd774532-cd89-453f-ab61-1da3e02351b7)
I hope that in the next version I can uninstall winmac with a script, and also update it to the latest version.

**Comment by adamkamienski** [comment]
Recycle bin removal is by design, as bin is put into explorer and dock to imitate macos eperience, which doesn't have recycle bin at desktop.

**I thought that the uninstall.ps1 file was also used to uninstall winmac, but it is not.**

It is, I jsut forgot to remove description in install.ps1 file, will update it today.

**Comment by Asteski** [comment]
Hello,

Recycel Bin removal is by design, it's moved to explorer and dock, to resemble macos design, which doens't include Recycel bin on desktop.

> I thought that the uninstall.ps1 file was also used to uninstall winmac, but it is not.

It is, but I forgot to remove description form install script, will do ti today.

**Comment by Dhyfer1** [comment]
> Recycle Bin removal is by design, it's moved to explorer and dock to resemble macos, which doesn't include Recycle bin on desktop by default.

In the latest version, 0.3.3, the script removes the Recycle bin even if I have selected the option to be installed using option 7.

> It is, but I forgot to remove description from install script, will update it today and I will include bringing back recycle bin to desktop as well, thanks for noticing.

As I said before, the recycle bin is removed when installing winmac. Here is a screenshot of the options I chose before installing the desired components

![Screenshot 2024-05-07 183937](https://github.com/Asteski/WinMac/assets/50301201/f8cd8a4f-fe61-4caa-8419-a745c4843b88)

This is another screenshot with the components installed before restarting the PC. Note that the recycle bin was removed, and the blue shortcut arrows were replaced with a blank icon.

![Screenshot 2024-05-07 184857](https://github.com/Asteski/WinMac/assets/50301201/9aed9303-9443-4c2e-aee6-dcb420e24dc8)

After restarting the pc, the recycle bin still does not appear, and the shortcuts continue with a blank document icon instead of the classic blue arrow.

In the uninstallation process, see the error that shows winmac when uninstall openshell, this error can be solved when the Windows Explorer task is finalized from the task manager (In Task Manager right click on Windows Explorer>End task) before running the uninstall script.

![Screenshot 2024-05-07 124540](https://github.com/Asteski/WinMac/assets/50301201/9929f318-da18-4ea2-827b-f5de1eac33e0)

When the script finished the custom uninstallation of the selected components, I reboot the pc and log in, but I see that the uninstallation was incomplete. As you can see in the following screenshot, the recycle bin still does not appear and the file explorer icon in the taskbar should not be expanded to display the tab title, and not only that, change the normal view to a compact view both in the navigation panel and in the file explorer area, besides it does not return the icons to the center of the taskbar.

![Screenshot 2024-05-07 125154](https://github.com/Asteski/WinMac/assets/50301201/245240cc-025b-433c-b00d-d89c7f818bb4)

**Comment by Dhyfer1** [comment]
Thank you so much. The new custom install and uninstall script work very well, although the only thing I don't like is that after installing Winmac the recycle bin disappears from the desktop. 🫤

I thought that the uninstall.ps1 file was also used to uninstall winmac, but it is not. ![ResizedImage_2024-05-05_23-59-21_2638.png](https://github.com/Asteski/WinMac/assets/50301201/dd774532-cd89-453f-ab61-1da3e02351b7)
I hope that in the next version I can uninstall winmac with a script, and also update it to the latest version.


Thank you. Take your time, I'll keep an eye out for the next version.

**Comment by Asteski** [comment]
@Dhyfer1 can you please test the latest version (by cloning _main_ branch) and let me know if issues still remain? Also please provide me an info about which version of os do you have, as in if it's either home or pro, and which os build.

**Comment by Dhyfer1** [comment]
> @Dhyfer1 can you please test the latest version (by cloning _main_ branch) and let me know if issues still remain? Also please provide me an info about your os edition, os version and os build.

Hi. I have already tested the latest version of winmac, 0.3.4, but it still has some problems, very small ones. For example, after installing winmac we still have the problem with the recycle bin, it still doesn't appear after installation. Also the blue arrows in the desktop shortcuts no longer appear, only the icon appears but without the blue arrow, although it looks good without the arrows, I don't know if this is a planned change that you forgot to mention in the changelog or if it is a new bug.

The problems I mentioned before when uninstalling winmac, such as the icons in the taskbar not returning to the center, or that the recycle bin can did not appear on the desktop, or that the Windows Explorer icon on the taskbar was expanding, or that when the explorer was opened it remained with compact view, all these problems that you already saw in my last screenshot have been fixed.

After uninstalling everything goes back to the way it was before installing winmac, except the folder icon for my username, as you can see in the following screenshot

![Untitled](https://github.com/Asteski/WinMac/assets/50301201/5eb61372-4a6b-4114-9dfa-d483e5749019)

Other than that, so far I have not found any other errors. 

Using winmac 0.3.4 on Windows 11 23H2 stable version, build 22631.3593

**Comment by Dhyfer1** [comment]
> Both changes - removal of recycle bin icon from desktop 

@akamienski, in latest versions of winmac, @Asteski added an option to install recycle bin in custom installation, as you can see in the screenshot my custom installation also includes option 7, where several things are installed, including the recycle bin, but the recycle bin is not installed even when I have selected option 7

![Screenshot 2024-05-07 183937](https://private-user-images.githubusercontent.com/50301201/328713360-f8cd8a4f-fe61-4caa-8419-a745c4843b88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzk3MzEsIm5iZiI6MTcxNjE3OTQzMSwicGF0aCI6Ii81MDMwMTIwMS8zMjg3MTMzNjAtZjhjZDhhNGYtZmU2MS00Y2FhLTg0MTktYTc0NWM0ODQzYjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA0MzAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZGRjNzgwMjViNWI4YWMwYWY3MDAwMzRhMTZiYzE1MjAwYjQ0NWU4MjEwNzJhNDQyMjhjMTc3Y2U2NzRkY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-24Gf-FmqTs9xlkyZfPym60_VJ_MWig8WbnsGYtOjdk)

> and removal of shortcut arrow are intended changes to resemble MacOS design. 

So it's not a bug. It's okay, no problem

**Comment by Dhyfer1** [comment]
> @Dhyfer1 is ther anything else I can help you with, or can I close the issue?

Well, winmac still has problems with the recycle bin in the latest version 0.4.1

In this screenshot I am doing a custom installation, see that the recycle bin icon is on the desktop and I did not choose option 8 to remove it

![1select components before install.png](https://github.com/Asteski/WinMac/assets/50301201/496583ec-07b9-4aa6-9dca-36fa9ddafd29)

In this screenshot, before rebooting after installation, see that the recycle bin icon was removed without my permission.

![2ask reboot after install.png](https://github.com/Asteski/WinMac/assets/50301201/19d7bf6f-4bba-46e0-960a-b05f5e36ac09)

This is what appears after reboot, recycle bin still missing

![3reboot after install.png](https://github.com/Asteski/WinMac/assets/50301201/ec49178e-7068-42ef-becf-8851d8c0c0d1)

In this screenshot I am doing a custom uninstallation, see that the recycle bin icon still missing, I am uninstalling the same components that I had shown in the first screenshot 

![4select components before uninstall.png](https://github.com/Asteski/WinMac/assets/50301201/ed1b877c-d49a-4a35-83a4-d5a4483d6cfa)

In this screenshot, before rebooting to complete the uninstall, shouldn't it say Uninstalling StartAllBack completed?

![5ask reboot after uninstall.png](https://github.com/Asteski/WinMac/assets/50301201/6936a48a-b7e2-4633-9d95-c272ea96df07)

Finally, after rebooting, the taskbar, start menu, and file explorer are back to normal, but the recycle bin still doesn't appear. I had to manually add the recycle bin shortcut from the themes settings in Windows 

![6reboot after uninstall.png](https://github.com/Asteski/WinMac/assets/50301201/1a6c8810-5299-4c67-b8ae-556fdd252a5c)

I hope the dev can find the solution for this, that's all.

**Comment by Dhyfer1** [comment]
> @Dhyfer1 is ther anything else I can help you with, or can I close the issue?

Well, winmac still has problems with the recycle bin in the latest version 0.4.1

In this screenshot I am doing a custom installation, see that the recycle bin icon is on the desktop and I did not choose option 8 to remove it

![1select components before install.png](https://github.com/Asteski/WinMac/assets/50301201/496583ec-07b9-4aa6-9dca-36fa9ddafd29)

In this screenshot, before rebooting after installation, see that the recycle bin icon was removed without my permission.

![2ask reboot after install.png](https://github.com/Asteski/WinMac/assets/50301201/19d7bf6f-4bba-46e0-960a-b05f5e36ac09)

This is what appears after reboot, recycle bin still missing

![3reboot after install.png](https://github.com/Asteski/WinMac/assets/50301201/ec49178e-7068-42ef-becf-8851d8c0c0d1)

In this screenshot I am doing a custom uninstallation, see that the recycle bin icon still missing, I am uninstalling the same components that I had shown in the first screenshot 

![4select components before uninstall.png](https://github.com/Asteski/WinMac/assets/50301201/ed1b877c-d49a-4a35-83a4-d5a4483d6cfa)

In this screenshot, before rebooting to complete the uninstall, shouldn't it say Uninstalling StartAllBack completed?

![5ask reboot after uninstall.png](https://github.com/Asteski/WinMac/assets/50301201/6936a48a-b7e2-4633-9d95-c272ea96df07)

Finally, after rebooting, the taskbar, start menu, and file explorer are back to normal, but the recycle bin still doesn't appear. I had to manually add the recycle bin shortcut from the themes settings in Windows 

![6reboot after uninstall.png](https://github.com/Asteski/WinMac/assets/50301201/1a6c8810-5299-4c67-b8ae-556fdd252a5c)

I hope the dev can find the solution for this, that's all.

**Comment by Dhyfer1** [comment]
> @Dhyfer1 Is there anything else I can help you with or can I close the issue?

There is something else. I've been using the latest version 0.5.2 and it has problems both installing and uninstalling. In the screenshot you can see the components I want to install

![Screenshot 2024-08-26 180557](https://github.com/user-attachments/assets/8202bacc-bc2f-461d-8bf1-e4fb3265576c)

Installs some components until it gets stuck in the Winmac menu installation, in this screen it remains unchanged for a long time.

![Screenshot 2024-08-26 191540](https://github.com/user-attachments/assets/ba1b2ef2-135c-4565-bdb6-ee5337cc41a5)

This is the uninstallation, in this part it was able to uninstall the Winmac menu, but it gets stuck trying to uninstall TopNotify. I could not take a screenshot when trying to uninstall TopNotify, because the Windows Explorer process was closed during the uninstall process.

![Screenshot 2024-08-26 201010](https://github.com/user-attachments/assets/c62dcb6c-da61-48f8-ba6f-8d977dde67a9)

After the failed uninstall, I reboot my pc and find that autohotkey was installed when I didn't ask for it. Here it appears in the start menu.

![Screenshot 2024-08-26 213815](https://github.com/user-attachments/assets/9ebbf537-8712-481d-a677-b69f43dee26c)

And not only that, in this and previous versions, every time I uninstall winmac the recycle bin icon does not appear on the desktop, I always have to add the icon manually from the Windows settings.

**Comment by Dhyfer1** [comment]
1. Windows 11 64bits stable, version 23H2 build 22631.4037

2. I chose the same options as in the first screenshot: 2, 4, 5, 6 y 9 but it keeps getting stuck on installing Winmac menu. The options I chose for the Winmac menu were: rounded shell corners and dark themed

3. Understood. So it is part of the Winmac menu.

4. In my previous message, you can see that I am including option 9 "Others" on installation and also option 10 "Others" on uninstallation, but on uninstallation it also gets stuck on some component, I don't know what else to do about it, I could install previous versions of Winmac without any problem. Maybe Winmac requires the computer to have some specific version of visual c++ redistributable or .net framework installed in order for it to work?

**Comment by Dhyfer1** [comment]
Sorry, in point 2 of my previous answer I forgot to mention that I used the installation and uninstallation scripts of debug version, but Winmac still can't be installed without any component getting stuck in the process.

This week I will reinstall Windows and then I will reinstall Winmac to see if the problem continues or not after a clean install of Windows

>and also installs .Net 6.0 Runtime x64 package.

I have .net desktop runtime 8.0 installed, maybe this is the problem? I will try installing version 6.0

**Comment by Asteski** [comment]
> I have .net desktop runtime 8.0 installed, maybe this is the problem? I will try installing version 6.0 to see if anything changes.

This shouldn't matter, because version 6.0 is installed with WinMac Menu component, so one shouldn't block the other from installing. If issue will persist, I'll then compile the executable to 8.0 version instead.

**Comment by Dhyfer1** [comment]
Update: Nothing, I have reinstalled Windows but I still have the same problem. In a custom installation with options 2, 4, 5, 6 and 9 it gets stuck on installing the winmac menu, so I closed the PowerShell window and rebooted the system.

In custom uninstall with options 2, 4, 5, 6 and 10, it shows me that it was able to uninstall winmac menu but it gets stuck on uninstalling topnotify, so I closed the PowerShell window and rebooted the system. Then I use a restore point I had created before installing winmac.

As I said before, winmac does not install/uninstall properly on a clean installation of Windows. Before installing winmac I did not install the latest version of visual v++ redistributable and also no version of .net framework. I don't bother trying with the debug version of winmac because I know I'll get the same result.

Tested on Windows 11 Pro version 23H2 build 22631.4112

**Comment by Asteski** [comment]
I've updated debug script to include .Net 8.0 version of WinMac Menu component, you can try that as well. I have no other ideas why it may not work, as when I've tested it on 3 new VM instances and 2 new laptops with both 23H2 and 24H2, it worked on all of them so I'm not able to recreate the issue. Do you happen to use 3rd party antivirus or local user account?

**Comment by Dhyfer1** [comment]
> Sorry, in point 2 of my previous answer I forgot to mention that I used the installation and uninstallation scripts of debug version, but Winmac still can't be installed without any component getting stuck in the process.

Sorry, this answer was wrong. When I said that I didn't know how to download the debug version, that time I just changed from Main to Debug, and I downloaded the latest version release thinking it was the latest debug version because I didn't know how to download the debug version. I thought I was downloading correctly but I was wrong and confused. I thought my problem would have been solved earlier if I had known how to download the debug version.

Now I know how to download it. So I ran both scripts and winmac was able to install and uninstall without any problems, this debug version worked very well, thanks.

>I'll just shoot blanks here, but do you happen to use:

>3rd party antivirus,
>unsupported processor,
>local user account.

If you still need that information, then:
- None, just the one that comes with Windows 11. Windows Defender
- Maybe this is it? I did not install Windows 11 the official way, I had to use Rufus because my processor is not supported, besides my PC doesn't have TPM or secure boot
- No, both scripts were executed under the administrator account

>Please provide me a specific processor name/model.

AMD Radeon HD 6310 Graphics, it's the processor that came in my laptop that I bought 13 years ago.

**Comment by Dhyfer1** [comment]
> Sorry, in point 2 of my previous answer I forgot to mention that I used the installation and uninstallation scripts of debug version, but Winmac still can't be installed without any component getting stuck in the process.

Sorry, this answer was wrong when I said that I used the installation and uninstallation scripts of debug version, that time I just changed from Main to Debug, and I downloaded the latest version release thinking it was the latest debug version because I didn't know how to download the debug version. I thought I was downloading correctly but I was wrong and confused. I thought my problem would have been solved earlier if I had known how to download the debug version.

Now I know how to download it. So I ran both scripts and winmac was able to install and uninstall without any problems, this debug version worked very well, thanks.

>I'll just shoot blanks here, but do you happen to use:

>3rd party antivirus,
>unsupported processor,
>local user account.

If you still need that information, then:
- None, just the one that comes with Windows 11. Windows Defender
- Maybe this is it? I did not install Windows 11 the official way, I had to use Rufus because my processor is not supported, besides my PC doesn't have TPM or secure boot
- No, both scripts were executed under the administrator account

>Please provide me a specific processor name/model.

AMD Radeon HD 6310 Graphics, it's the processor that came in my laptop that I bought 13 years ago.

**Comment by Asteski** [comment]
Thanks for leting me know, I'll update next version with changes included in debug script. Is there any difference when you choose either .Net 8.0 and .Net 6.0 version?

**Comment by Dhyfer1** [comment]
In the installation I chose .Net 8.0, I don't know if there is a difference in the installation with .Net 6.0. You said no before, but I don't think there is any. 🤷

**Comment by Asteski** [comment]
It shouldn't be theoretically, I'll include .Net 8.0 version then anyway.

**Comment by Dhyfer1** [comment]
That's ok. Now that my problem has been solved (at least on the debug version) I will close this issue, thank you both for your help. :D

**Comment by Asteski** [comment]
You're welcome! FYI It's only me, using both accounts interchangibly.

**Comment by Dhyfer1** [comment]
> Is there any difference when you choose either .Net 8.0 and .Net 6.0 version?

So I reinstalled winmac, this time I chose .Net 6.0 and found no difference.

By the way, when I installed winmac debug with both versions of .net separately, I noticed that it also installs Aspnet core runtime, I didn't have this before installing the stable version of winmac. Maybe because I didn't have aspnet installed at the beginning, Winmac was giving me problems when I wanted to install the stable version? 

Also, I have noticed on both installations of winmac debug with .net 6 and 8, that when I click on the Windows icon in the taskbar repeatedly or press the Windows button repeatedly, sometimes the normal Windows menu appears. You should check it.

**Comment by Dhyfer1** [comment]
@Asteski I have installed the latest stable version of winmac, 0.6.0, and it downloads and installs .Net Desktop Runtime 8.0 when I already had it installed, I wanted to let you know. By the way, there have been no problems installing/uninstalling winmac.

In addition, I also wanted to know if you can integrate [mactype](https://github.com/snowie2000/mactype) MacType is a free tool that allows you to render Windows fonts to be similar to Mac OS fonts. I think it's a great addition to winmac.
