### ISSUE TITLE
How i can install?

### ISSUE THREAD

**Issue by MrNico98** [Asteski/WinMac#10]
Hi everyone, how can I install it?

**Comment by Asteski** [comment]
Hello,

- First, you should download and install the latest version of winget using [MS Store](https://apps.microsoft.com/detail/9nblggh4nns1?rtc=1&hl=pl-pl&gl=PL#activetab=pivot:overviewtab). 

- Install latest powershell core version, using winget command: _winget install --id Microsoft.PowerShell_

- Download a zip file of [latest release](https://github.com/Asteski/WinMac/releases/tag/v0.4.1), unpack it and run _install.ps1_ script using elevated powershell core session (run pwsh as admin). Everything else will be installed automatically.

Enjoy!

Please keep in mind that WinMac is tested only on the latest Windows 11 stable build, so no insiders builds are supported.
