### ISSUE TITLE
Wallpaper engine not resuming after sleep.

### ISSUE THREAD

**Issue by dalicode** [Asteski/WinMac#21]
Is there a script that is breaking wallpaper engine somehow?

**Comment by Asteski** [comment]
Not really, no part of script is configuring wallpaper. Which wallpaper engine you use?

**Comment by dalicode** [comment]
The steam one called Wallpaper Engine

**Comment by Asteski** [comment]
@dalicode That's more likely, as Rectify11 replaces many crucial Windows files, that may impact other software that may use them. Uninstall Themes component of Rectify11 if you do installed it, it uses UX Theme Patcher that may impact wallpaper engines.

**Comment by dalicode** [comment]
Thanks ill look into it
