### ISSUE TITLE
Installing it broke everything.

### ISSUE THREAD

**Issue by iBlazeX** [Asteski/WinMac#5]
My start menu stopped working. I had to uninstall Open Shell to fix that.

![image](https://github.com/Asteski/WinMac/assets/85124169/162a87b2-b479-4478-90ad-a6d0fcacbb06)
My icons now look like this with a weird blank icon in front.

Nexus Dock that was installed was not configured. It didn't have any customization.

Uninstall.ps1 doesn't work and shows an error.
![image](https://github.com/Asteski/WinMac/assets/85124169/e16d95cf-5ac6-45ad-8533-0742c823692f)

Also, StartAllBack was not installed as it showed an error during installation that it was not compatible and can slow down the device.  

It created a mess, which I now have to clean manually. 

Edit: using uninstall.bat from 0.3.4 version works and doesn't show that error.

**Comment by Asteski** [comment]
Hello, 
which version of os do you have, as in if it's either home or pro, and which os build. 

So now you have only an issue with shortcut icons, or issue with Nexus still persist?

**Comment by iBlazeX** [comment]
Edition	Windows 11 Pro for Workstations
Version	24H2
Installed on	‎08-‎04-‎2024
OS build	26120.470
Experience	Windows Feature Experience Pack 1000.26100.6.0

After uninstallation using uninstall.ps1, the issue with icons is gone. 
And Nexus issue was still there. So, I uninstalled it as well. 
SAB didn't install at all, as it shown a compatibility error. 

Yes, I ran the installer with admin privileges. And I cloned the main branch first, which had faulty uninstall.ps1 file. So, I tried uninstall.ps1 from v0.3.4, which worked.  

![image](https://github.com/Asteski/WinMac/assets/85124169/a7a056ef-35af-425d-9b8e-b8d2b8a849a7)
I had this exact same error. (Found pic from internet) 
This is actually a known issue on W11. 

https://www.elevenforum.com/t/startallback-error.24340/ for reference.

**Comment by Asteski** [comment]
Okay but isn't this version from dev channel, as in an Insider Preview Build, according to [this page](https://blogs.windows.com/windows-insider/2024/05/10/announcing-windows-11-insider-preview-build-26120-470-dev-channel/)? WinMac is and will only be tested on stable builds.

**Comment by iBlazeX** [comment]
Oh yes, it is dev build. I didn't know it would cause problems. SAB problem is understandable and a known issue. I wonder why all those other issues occurred.
